import os

KAFKA_INTERNAL_PORT = os.environ.get("KAFKA_INTERNAL_PORT", "9092")
KAFKA_BROKER_URL = f'kafka:{KAFKA_INTERNAL_PORT}'

ORDER_KAFKA_TOPIC = "order_details"
ORDER_CONFIRMED_KAFKA_TOPIC = "order_confirmed"
ALL_KAFKA_TOPICS = [ORDER_KAFKA_TOPIC, ORDER_CONFIRMED_KAFKA_TOPIC]

DEFAULT_ORDER_LIMIT = 250
DEFAULT_ORDER_START_SECONDS = 5
DEFAULT_ORDER_WAIT_SECONDS = 1

ADMIN_CLIENT_ID = 'admin-client'
PRODUCER_CLIENT_ID = 'orders-backend'
TRANSACTION_CLIENT_ID = 'transactions-backend'
EMAIL_CLIENT_ID = 'email-backend'
ANALYTICS_CLIENT_ID = 'analytics-backend'
