import os

KAFKA_INTERNAL_PORT = os.environ.get("KAFKA_INTERNAL_PORT", "9092")
KAFKA_BROKER_URL = f'kafka:{KAFKA_INTERNAL_PORT}'

ORDER_KAFKA_TOPIC = "order_details"
ORDER_CONFIRMED_KAFKA_TOPIC = "order_confirmed"

ORDER_LIMIT = 250
ORDER_START_SECONDS = 5
ORDER_WAIT_SECONDS = 1

# PRODUCER_CLIENT_ID = 'fastapi-producer'
